format = """
[░▒▓](#5f8787)\
[  ](bg:#5f8787 fg:#000000)\
[](bg:#505050 fg:#5f8787)\
$directory\
[](fg:#505050 bg:#333333)\
$git_branch\
$git_status\
[](fg:#333333 bg:#121212)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#121212)\
\n$character"""

[directory]
style = "fg:#fbcb97 bg:#505050"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol $branch ](fg:#5f8787 bg:#333333)]($style)'

[git_status]
style = "bg:#333333"
format = '[[($all_status$ahead_behind )](fg:#5f8787 bg:#333333)]($style)'

[nodejs]
symbol = ""
style = "bg:#121212"
format = '[[ $symbol ($version) ](fg:#5f8787 bg:#121212)]($style)'

[rust]
symbol = ""
style = "bg:#121212"
format = '[[ $symbol ($version) ](fg:#5f8787 bg:#121212)]($style)'

[golang]
symbol = ""
style = "bg:#121212"
format = '[[ $symbol ($version) ](fg:#5f8787 bg:#121212)]($style)'

[php]
symbol = ""
style = "bg:#121212"
format = '[[ $symbol ($version) ](fg:#5f8787 bg:#121212)]($style)'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#000000"
# format = '[[  $time ](fg:#999999 bg:#000000)]($style)'
